language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql
before_script:
  - psql -c 'create database order3_test_db;' -U postgres
# command to run tests

script: pytest -v 

after_success:
  - coveralls
